name: "Validate: hassfest + HACS"

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/**'
      - 'hacs.json'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6

      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master

      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
